-- MySQL Script generated by MySQL Workbench
-- sáb 01 out 2022 21:04:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db` DEFAULT CHARACTER SET utf8 ;
USE `db` ;

-- -----------------------------------------------------
-- Table `mydb`.`Caixas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Caixas` (
  `idCaixas` INT NOT NULL AUTO_INCREMENT,
  `nome_caixas` VARCHAR(45) NULL,
  PRIMARY KEY (`idCaixas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Doacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`Doacoes` (
  `idDoacoes` INT NOT NULL AUTO_INCREMENT,
  `horario_doacao` INT NOT NULL,
  `classe_doacao` VARCHAR(45) NOT NULL,
  `fk_caixa` INT NOT NULL,
  PRIMARY KEY (`idDoacoes`),
  CONSTRAINT `fk_caixa`
    FOREIGN KEY (`fk_caixa`)
    REFERENCES `mydb`.`Caixas` (`idCaixas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Caixas`
-- -----------------------------------------------------
START TRANSACTION;
USE `db`;
INSERT INTO `db`.`Caixas` (`idCaixas`, `nome_caixas`) VALUES (1, 'EST');
INSERT INTO `db`.`Caixas` (`idCaixas`, `nome_caixas`) VALUES (2, 'ESO');
INSERT INTO `db`.`Caixas` (`idCaixas`, `nome_caixas`) VALUES (3, 'ENS');
INSERT INTO `db`.`Caixas` (`idCaixas`, `nome_caixas`) VALUES (4, 'ESAT');
INSERT INTO `db`.`Caixas` (`idCaixas`, `nome_caixas`) VALUES (5, 'Manauara');
INSERT INTO `db`.`Caixas` (`idCaixas`, `nome_caixas`) VALUES (6, 'Sumauma');

COMMIT;
